import 'bootstrap-icons/font/bootstrap-icons.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Prompt } from 'next/font/google'
import NavigationWrapper from './component/NavigationWrapper'

const prompt = Prompt({
  subsets: ['thai', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
})

export const metadata = {
  title: 'เว็บไซต์สนุ๊กเกอร์',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <NavigationWrapper />
        {children}
      </body>
    </html>
  )
}
